name: Markdown Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            *.md
            docs/*.md
            content/*.md